Fixing Import GitHub repository list
falko-org/Falko pull request #102
Opened 2017-11-05 15:10 UTC by pedrokelvin

Signed-off-by: Pedro Kelvin <pedrokelvin2006@gmail.com>

## Mudanças Propostas

Descreva brevemente as mudanças feitas. Tenha certeza que linkou o pull request à uma issue existente.

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [x] Conserto de Bug
- [ ] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [ ] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [ ] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros de linter.
- [ ] A build está passando (testes, code climate e codacy).
- [ ] O pull request está linkado à uma issue existente.

## Screenshots
Se  possível, incluir screenshots das modificações  feitas.

## Outros Comentários
Se for uma mudança relativamente grande/complexa e você tiver algum comentário/pergunta a fazer, explicação de sua escolha da sua solução ou qualquer coisa que ache relevante, não hesite em compartilhar.

2017-11-05 18:42 UTC, alaxalves commented
@pedrokelvin Altere o template do PR

2017-11-05 18:43 UTC, alaxalves commented
![image](https://user-images.githubusercontent.com/19597045/32417962-6ac21574-c248-11e7-9fc0-77424e96cfce.png)
Esses testes não estão passando, arrume eles e atualiza o PR

2017-11-05 18:43 UTC, pedrokelvin commented
@alaxalves onde??

2017-11-05 19:00 UTC, pedrokelvin commented
O template agora do PR está correto.

2017-11-05 22:17 UTC, alaxalves commented
Beleza, só falta dar uma ajeitada nesses testes que fica bom

2017-11-05 22:46 UTC, pedrokelvin commented
Os testes foram arrumados e agora está tudo certo para o Merge.

2017-11-06 10:47 UTC, alaxalves commented
Muito bom Pedro!! @pedrokelvin Antes de mergir, poderia adicionar um prints de tela que mostram as modificações que voce fez nessa listagem???

2017-11-06 12:20 UTC, pedrokelvin commented
![captura de tela de 2017-11-06 10-16-47](https://user-images.githubusercontent.com/18222839/32440790-e19e0750-c2db-11e7-897b-02b6b2208333.png)
A mudança ocorreu apenas na linha 86 pois agora o JSON está chegando de maneira diferente, então teve que ser adaptado o acesso ao vetor de dados que chega à aplicação. Mas a listagem continua da mesma forma, foi apenas consertado um bug.

2017-11-06 12:26 UTC, MatheusRich requested changes
Remova a pasta test/unit/coverage, pois ela não deve ser commitada. Além disse, tenha atenção ao remover com os 'console.log()'.

2017-11-06 12:36 UTC, pedrokelvin commented
@alaxalves não ocorreram mudanças visuais na listagem, ela está da mesma forma. O que ocorreu foi uma adaptação ao acesso do vetor de dados que chega à aplicação, pois agora ele está diferente. Mas a listagem continua igual, foi apenas consertado um bug.

2017-11-06 12:54 UTC, pedrokelvin commented
@MatheusRich pronto, a pasta foi removida.

2017-11-06 13:13 UTC, MatheusRich approved these changes

2017-11-06 13:14 UTC, merged