Criar Sidebar
falko-org/Falko pull request #103
Opened 2017-11-05 20:47 UTC by MateusO97

## Mudanças Propostas

Adicionar uma sidebar ao projeto para facilitar a navegação.

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [x] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [x] Não há erros de linter.
- [ ] A build está passando (testes, code climate e codacy).
- [x] O pull request está linkado à uma issue existente.

## Screenshots
Se  possível, incluir screenshots das modificações  feitas.

## Outros Comentários
Se for uma mudança relativamente grande/complexa e você tiver algum comentário/pergunta a fazer, explicação de sua escolha da sua solução ou qualquer coisa que ache relevante, não hesite em compartilhar.

2017-11-06 10:29 UTC, MatheusRich commented
A build não está passando. Adicione screenshots para visualizarmos as modificações feitas

2017-11-06 10:44 UTC, alaxalves commented
![image](https://user-images.githubusercontent.com/19597045/32437455-93c9dba6-c2ce-11e7-9142-38660f5e3150.png)
@MateusO97 Ta aí o print do log de erro do travis

2017-11-06 12:29 UTC, MatheusRich requested changes
A build não está passando. Adicione screenshots para visualizarmos as modificações feitas.

Outra dúvida: para que foi adicionado JQuery?

2017-11-06 22:44 UTC, MateusO97 commented
![releases](https://user-images.githubusercontent.com/27258892/32467817-089961d6-c333-11e7-803e-e7f8c8d1617f.png)
A sidebar ficou assim. Não tem como mostrar os popovers mas quando o usuário passa o cursor em cima aparece um popover falando qual o nome do componente. A aba de sprints só aparece quando o usuário estiver dentro de uma release e a de release somente quando ele tiver dentro de um projeto.

2017-11-06 22:48 UTC, MateusO97 commented
Tinha adicionado o JQuery porque muitas pessoas que tiveram esse mesmo erro que o log do travis apontou, mesmo já tendo o bootstrap ou o vue que não necessitária dele, disseram que resolveu. Por isso coloquei para testar mas mesmo assim não identificou. O componente esta funcionando normalmente tanto que esse erro é na função do popover que está funcionando normalmente na aplicação, mas vou procurar outra solução.

2017-11-07 11:45 UTC, MatheusRich commented
@MateusO97 A dúvida não foi porque você adicionou o source do JQuery, e sim para que você está usando JQuery. Acredito que a função que você está utilizando pode ser substituída por algo padrão do Vue.js, não?

2017-11-07 15:34 UTC, MateusO97 commented
@MatheusRich o popover parece que pra funcionar precisa do JQuery mesmo, no próprio bootstrap vem falando isso. To tentando achar se tem algo parecido no Vue, achei uma biblioteca só. Mas vou testar outra coisa antes

2017-11-08 04:26 UTC, MateusO97 commented
Obrigado pela sugestão @MatheusRich encontrei uma função padrão do VueJs para resolver isso e assim simplificou bastante o código. Atualmente a Sidebar está assim: 
![popover_funcionando](https://user-images.githubusercontent.com/27258892/32531635-1e99d5b6-c42c-11e7-9f7c-330814d9d91e.png)

2017-11-08 12:37 UTC, alaxalves requested changes
Outra coisa, esse elemento aparece em todas as páginas? Porque ele não deveria aparecer quando o usuário não está logado. @MateusO97

2017-11-08 12:37 UTC, alaxalves commented on index.html
>      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
Isso precisa ser removido, já que importa o JQuery e a gente não ta utilizando mais @MateusO97

2017-11-08 14:46 UTC, MateusO97 commented on index.html
>      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
@alaxalves Ele aparece somente quando o usuário está logado, e o componente de Releases só se torna visivel quando o usuário esta dentro de um projeto, assim como o de Sprints só pode ser visto dentro de alguma release. Esse code.jquery que ele está importando não fui eu quem adicionou, ele já estava na Devel, alguem deve está utilizando em outra parte do código

2017-11-08 14:52 UTC, MatheusRich commented
@MateusO97 Só uma última coisa. Seria interessante ter a sidebar de cor diferente da navbar. Seguem alguns exemplos:

![image](https://user-images.githubusercontent.com/20938712/32555366-aaa0b2bc-c483-11e7-8798-42a9ef499b8b.png)

![image](https://user-images.githubusercontent.com/20938712/32555372-af605802-c483-11e7-8cca-78d2ef327267.png)

![image](https://user-images.githubusercontent.com/20938712/32555380-b424a3ca-c483-11e7-9e6d-2cc73990e51a.png)

2017-11-09 02:06 UTC, MatheusRich approved these changes

2017-11-09 12:06 UTC, alaxalves commented on index.html
>      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
@MateusO97 Beleza, conversando com a galera eu vi que estava errado, vou aceitar!!

2017-11-09 12:06 UTC, alaxalves approved these changes

2017-11-09 12:07 UTC, alaxalves commented
Resolve a issue https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd/issues/51

2017-11-09 12:07 UTC, merged