Realizando visualização de GPA em cada projeto importado através do GitHub
falko-org/Falko pull request #110
Opened 2017-11-06 15:59 UTC by pedrokelvin

## Mudanças Propostas

Métrica de GPA sendo visualizada dentro de cada projeto importado através da opção Importar GitHub Repository

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [x] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros de linter.
- [ ] A build está passando (testes, code climate e codacy).
- [ ] O pull request está linkado à uma issue existente.

## Screenshots

## Outros Comentários

2017-11-07 22:36 UTC, MatheusRich requested changes
Resolvam o conflito e coloquem screenshots do que foi desenvolvido.

2017-11-07 23:05 UTC, alaxalves commented
O conflito foi resolvido por ora, mas adicionem prints de tela das coisas que vcs mudaram por favor!!

2017-11-07 23:42 UTC, MatheusRich commented
O componente de GPA podia estar dentro do card de Projects. Não coloquem a informação jogada na tela. Outra coisa, o componente podia ficar colorido de acordo com o valor do GPA (pior fica vermelho, por exemplo).

2017-11-08 21:22 UTC, pedrokelvin commented
@MatheusRich foram feitas as modificações de acordo com o pedido.

2017-11-09 12:03 UTC, alaxalves requested changes

2017-11-09 12:03 UTC, alaxalves commented on src/components/Projects/Project.vue
> +        <router-link v-bind:to="'/inproject/'+project.id+'/sprints'">
O path não é mais inproject!!

2017-11-10 13:29 UTC, pedrokelvin commented on src/components/Projects/Project.vue
> +        <router-link v-bind:to="'/inproject/'+project.id+'/sprints'">
Pronto.

2017-11-10 13:36 UTC, alaxalves submitted a review, later dismissed

2017-11-10 13:43 UTC, MatheusRich approved these changes

2017-11-10 13:45 UTC, MatheusRich submitted a review, later dismissed

2017-11-10 13:45 UTC, MatheusRich commented on src/components/Gpa.vue
> +.GpaFont {
Trocar classes de camelCase para kebab-case

2017-11-10 14:01 UTC, alaxalves commented
Apareceram alguns conflitos @pedrokelvin resolve eles que estará pront pro merge.

2017-11-10 19:26 UTC, alaxalves approved these changes

2017-11-10 19:28 UTC, merged

2017-11-10 19:29 UTC, alaxalves commented
Resolve a Issue https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd/issues/113