Arrumando o tamanho da logo na página 404
falko-org/Falko pull request #117
Opened 2017-11-07 17:28 UTC by MateusO97

## Mudanças Propostas

DIminuir o tamanho da logo na página 404 para não aparecer o scroll.

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [x] Conserto de Bug
- [ ] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [x] Não há erros de linter.
- [x] A build está passando (testes, code climate e codacy).
- [x] O pull request está linkado à uma issue existente.

## Screenshots
![404](https://user-images.githubusercontent.com/27258892/32508003-14d145d4-c3d0-11e7-8f71-e4d759d4946a.png)

2017-11-07 21:09 UTC, MateusO97 commented
@MatheusRich  é para aumentar o tamanho da logo mas não deixar ficar grande a ponto de criar a barra de scroll ou desse tamanho ficou bom ? No meu computador esse novo tamanho que enviei já não está mais ficando com scroll.

2017-11-07 22:21 UTC, MatheusRich commented
@MateusO97 Dessa forma tá ok!

2017-11-07 22:25 UTC, MatheusRich requested changes
@MateusO97 No meu computador esse tamanho fica grande ainda. Tente usar um media query ou alguma opção para diferenciar tamanho de tela, e aí renderizar a imagem com tamanhos diferente de acordo com a resolução.

2017-11-10 01:28 UTC, MateusO97 commented
@MatheusRich Fiz algumas mudanças com o media query para varios tipos de dispositivo. Mas não sei muito bem como testar, se puder olhar de novo para me dar o feedback seria ótimo.

2017-11-10 14:10 UTC, alaxalves commented
![image](https://user-images.githubusercontent.com/19597045/32661987-1799702e-c610-11e7-8d8b-25432a2c0dac.png)
No meu PC continua grande @MateusO97 :|

2017-11-11 02:19 UTC, MatheusRich commented
No meu também!

2017-11-11 15:38 UTC, MatheusRich approved these changes

2017-11-11 15:44 UTC, MatheusRich commented
@MateusO97 arrumei para o PCs com resolução menor. Veja como fica no seu. Se estiver de boa, eu aceito o pull request.

2017-11-11 17:01 UTC, merged

2017-11-11 23:56 UTC, cantuariavc commented
Resolve a issue #115