Modificando cores da Sidebar
falko-org/Falko pull request #126
Opened 2017-11-09 15:20 UTC by MateusO97

## Mudanças Propostas

Ajustando cores da sidebar como forma de deixar seu visual mais _clean_.

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [x] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [x] Não há erros de linter.
- [x] A build está passando (testes, code climate e codacy).
- [x] O pull request está linkado à uma issue existente.

## Screenshots
![sidebar1](https://user-images.githubusercontent.com/27258892/32612852-73ff82f6-c550-11e7-8c57-072b1c25cfb5.png)
![sidebar2](https://user-images.githubusercontent.com/27258892/32612854-74513696-c550-11e7-95ef-281d0b43a877.png)
![sidebar3](https://user-images.githubusercontent.com/27258892/32612855-747a84d8-c550-11e7-9cda-ad70fb9f5560.png)

## Outros Comentários
Coloquei 3 opções de cores diferentes. Caso queiram que teste outras ou que mude a cor da navbar também avisem em um comentário.

2017-11-09 16:23 UTC, MatheusRich requested changes
Não tinha gostado de nenhuma das cores que você tentou. Tentei aqui também, mas não consegui chegar num resultado bom também. 

Faça o seguinte:

- Deixe a sidebar da msm cor da navbar. Coloque uma borda da cor #ddd nelas.
- Deixe os ícones da cor #3E5361
- Para alinhar os itens de forma correta, retire qualquer margin/border que vc tenha feito na mão e use align="center" nos "< li >"

2017-11-10 02:44 UTC, MateusO97 commented
![centralizar](https://user-images.githubusercontent.com/27258892/32640510-1d16d524-c5b0-11e7-91bf-53d8bb6b8415.png)
Adicionei a borda e ajustei as cores, porem não consegui alinhas elas corretamente com o align="center"

2017-11-10 13:45 UTC, alaxalves commented
@MateusO97 Os icones me parecem estar bem desalinhados :/

2017-11-10 14:12 UTC, alaxalves commented
@MateusO97 Apareceram alguns conflitos também.

2017-11-10 14:16 UTC, MatheusRich commented
@alaxalves Corrigido.

![image](https://user-images.githubusercontent.com/20938712/32662235-f8004c50-c610-11e7-9663-a6c077fdf82c.png)

2017-11-10 14:26 UTC, MatheusRich submitted a review, later dismissed

2017-11-10 18:46 UTC, ThalissonMelo commented
* Ícone de sprint se parece muito com ícone de recarregar página
* Ícone de sprint, release e projeto não tem funcionalidade quando estão em suas respectivas index
* Quando está dentro de uma sprint específica e clica no botão de sprint na navbar ele redireciona para a página de sprints errada(ele usa o id da sprint como o id da release e por isso há esse bug)

2017-11-10 18:55 UTC, ThalissonMelo approved these changes

2017-11-10 18:55 UTC, merged

2017-11-11 01:35 UTC, cantuariavc commented
Resolve a issue #125