Us06 designar membros
falko-org/Falko pull request #169
Opened 2017-11-14 23:29 UTC by drianne

## Mudanças Propostas

Essa funcionalidade permite atribuir um assignee à uma issue de um projeto existente.

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [ ] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [ ] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [ ] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros de linter.
- [ ] A build está passando (testes, code climate e codacy).
- [ ] O pull request está linkado à uma issue existente.

## Screenshots
Se  possível, incluir screenshots das modificações  feitas.

## Outros Comentários
Se for uma mudança relativamente grande/complexa e você tiver algum comentário/pergunta a fazer, explicação de sua escolha da sua solução ou qualquer coisa que ache relevante, não hesite em compartilhar.

2017-11-15 03:10 UTC, alaxalves commented
Muito legal @drianne

2017-11-15 03:11 UTC, alaxalves commented on src/router/index.js
> +    {
Realmente precisa dessa rota??

2017-11-15 03:12 UTC, alaxalves commented on src/components/Issues/Assignee.vue
> +        R odadO dadadL adad A
Remove esse texto aqui

2017-11-15 03:13 UTC, alaxalves commented on src/components/Issues/EditIssue.vue
> +        console.log("Sucesso")
Escreve em ingles

2017-11-15 03:13 UTC, alaxalves commented on src/components/GitHub/GitHubProjects.vue
> +        // REMOVE DEPOIS*******************************************************
acredito que realmente vc nao deve passar o slug na mão

2017-11-16 11:28 UTC, drianne commented on src/components/GitHub/GitHubProjects.vue
> +        // REMOVE DEPOIS*******************************************************
Retirei @alaxalves

2017-11-16 11:28 UTC, drianne commented on src/components/Issues/EditIssue.vue
> +        console.log("Sucesso")
Feito!

2017-11-16 11:28 UTC, drianne commented on src/components/Issues/Assignee.vue
> +        R odadO dadadL adad A
Removido ...

2017-11-17 13:54 UTC, MatheusRich commented
@drianne resolva os conflitos!

2017-11-21 11:07 UTC, MatheusRich requested changes

2017-11-21 11:07 UTC, MatheusRich commented on src/components/GitHub/GitHubProjects.vue
> +function doRequisitions(repos, length, user) {
Trocar para a nova sintaxe de funções:

```javascript
doRequisitions( ... ) {
   //código
}
```

2017-11-21 11:07 UTC, MatheusRich commented on src/components/GitHub/GitHubProjects.vue
> +    const rawToken = localStorage.getItem('token');
Trocar para Vuex.

2017-11-22 18:00 UTC, danieloda commented on src/components/GitHub/GitHubProjects.vue
> +    const rawToken = localStorage.getItem('token');
Tinham duas funções doRequisitions, retirei uma e a que ficou está com vuex.

2017-11-22 18:05 UTC, danieloda commented on src/router/index.js
> +    {
Não, já retirei

2017-11-23 11:56 UTC, MatheusRich approved these changes

2017-11-23 11:56 UTC, merged

2017-11-23 11:57 UTC, MatheusRich commented
Resolve a issue #134