Melhorando a página do usuário
falko-org/Falko pull request #177
Opened 2017-11-17 13:54 UTC by leossb36

## Mudanças Propostas

Melhorando o visual da página do usuário 

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [ ] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros de linter.
- [ ] A build está passando (testes, code climate e codacy).
- [x] O pull request está linkado à uma issue existente.

## Screenshots
Se  possível, incluir screenshots das modificações  feitas.

## Outros Comentários
Se for uma mudança relativamente grande/complexa e você tiver algum comentário/pergunta a fazer, explicação de sua escolha da sua solução ou qualquer coisa que ache relevante, não hesite em compartilhar.

2017-11-17 17:47 UTC, drianne commented
@leossb36 Coloca os prints de tela!

2017-11-17 19:49 UTC, alaxalves submitted a review, later dismissed

2017-11-18 23:58 UTC, MatheusRich commented
@leossb36 Resolva os conflitos utilizando VUEX agora.

2017-11-21 03:12 UTC, MatheusRich requested changes
Fazer merge com a devel e utilizar vuex

2017-11-30 12:28 UTC, MatheusRich approved these changes

2017-11-30 12:28 UTC, merged

2017-11-30 12:29 UTC, MatheusRich commented
Resolve a issue #116