US23 - Planejar Sprint
falko-org/Falko pull request #207
Opened 2017-11-27 13:21 UTC by danieloda

## Mudanças Propostas

História de planejar sprint. Organização das issues dentro de uma sprint através de um "kanban".

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [x] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [x] Não há erros de linter.
- [ ] A build está passando (testes, code climate e codacy).
- [ ] O pull request está linkado à uma issue existente.

## Screenshots
![ ](https://i.imgur.com/DCgzfkY.png)

## Outros Comentários
Se for uma mudança relativamente grande/complexa e você tiver algum comentário/pergunta a fazer, explicação de sua escolha da sua solução ou qualquer coisa que ache relevante, não hesite em compartilhar.

2017-11-27 15:24 UTC, alaxalves commented
@danieloda O PR nao esta conectado a uma issue

2017-11-27 15:30 UTC, alaxalves requested changes

2017-11-27 15:30 UTC, alaxalves commented on src/components/Projects/Project.vue
> +    setProjetId() {
Acredito q o nome está errado aqui, creio q seja _setProjectId_

2017-11-27 15:30 UTC, alaxalves commented on src/components/Projects/Project.vue
>        this.isFromProjectGitHub();
Esse nome ta muito esquisito, o correto seria _isProjectFromGitHub_ não???

2017-11-27 15:30 UTC, alaxalves commented on src/components/Stories/Stories.vue
> +            <h4>Backlog da Sprint&nbsp; &nbsp; </h4>
Está em Portugues

2017-11-27 15:30 UTC, alaxalves commented on src/components/Stories/Stories.vue
> +/*
Gostei pra caramba do fato de terem colocado comentarios.... facilita a interpretação.

2017-11-27 15:31 UTC, alaxalves commented
@MatheusRich Dei uma olhada superficial no codigo, também acompanhei parte do desenvolvimento dessa historia, se puder dar uma revisada também seria bom

2017-11-27 15:47 UTC, alaxalves commented
@danieloda Outra dúvida, essa história envolve apenas o FrontEnd mesmo?

2017-11-27 17:31 UTC, danieloda commented
Resolve a issue https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd/issues/209

2017-11-27 17:32 UTC, danieloda commented on src/components/Projects/Project.vue
>        this.isFromProjectGitHub();
esse método em especifico seta o id do projeto no storage do vuex, nao conseguiamos acessa-lo da forma como estava antes.

2017-11-27 17:39 UTC, danieloda commented on src/components/Stories/Stories.vue
> +            <h4>Backlog da Sprint&nbsp; &nbsp; </h4>
https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd/pull/207/commits/a6045f6e65debf7b6a698f0c39bf5443e0f60508

2017-11-27 17:39 UTC, danieloda commented on src/components/Projects/Project.vue
> +    setProjetId() {
https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd/pull/207/commits/a6045f6e65debf7b6a698f0c39bf5443e0f60508

2017-11-27 17:41 UTC, danieloda commented
@alaxalves Nao, tem backend tbm

2017-11-27 17:42 UTC, danieloda commented on src/components/Projects/Project.vue
>        this.isFromProjectGitHub();
https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd/pull/207/commits/a6045f6e65debf7b6a698f0c39bf5443e0f60508

2017-11-28 12:20 UTC, alaxalves submitted a review, later dismissed

2017-11-28 12:21 UTC, alaxalves commented
@danieloda Não consegui encontrar o PR no BackEnd

2017-12-02 14:29 UTC, alaxalves commented on src/components/Projects/Project.vue
>        this.isFromProjectGitHub();
Quis dizer que o problema é apenas o nome do método. O correto seria _isProjectFromGitHub_

2017-12-02 14:34 UTC, alaxalves requested changes

2017-12-02 14:34 UTC, alaxalves commented on src/components/Stories/Stories.vue
> +/*#doneCard:hover {
É necessário manter esse comentário?

2017-12-02 14:34 UTC, alaxalves commented on src/components/Stories/Stories.vue
> +/* .card */
É necessário manter esse comentários?????

2017-12-02 19:10 UTC, alaxalves requested changes

2017-12-02 19:10 UTC, alaxalves commented on src/components/Projects/Project.vue
>        this.isFromProjectGitHub();
Muda ae men @danieloda

2017-12-06 13:36 UTC, MatheusRich commented on src/components/Projects/Project.vue
>        this.isFromProjectGitHub();
@alaxalves O @cantuariavc alterou isso já em outra branch. Pode aceitar o PR.

2017-12-07 12:04 UTC, danieloda commented on src/components/Projects/Project.vue
>        this.isFromProjectGitHub();
@alaxalves

2017-12-07 12:06 UTC, alaxalves approved these changes

2017-12-07 12:06 UTC, alaxalves commented on src/components/Projects/Project.vue
>        this.isFromProjectGitHub();
Vou aceitar então

2017-12-07 12:06 UTC, alaxalves approved these changes

2017-12-07 12:07 UTC, merged

2017-12-07 12:08 UTC, alaxalves commented
Resolve a Issue #209