Us19 visualizar velocity
falko-org/Falko pull request #214
Opened 2017-11-30 06:12 UTC by Matheus456

## Mudanças Propostas

Visualização do velocity através do gráfico.

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [ ] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros de linter.
- [ ] A build está passando (testes, code climate e codacy).
- [ ] O pull request está linkado à uma issue existente.

## Screenshots
Se  possível, incluir screenshots das modificações  feitas.

## Outros Comentários
Se for uma mudança relativamente grande/complexa e você tiver algum comentário/pergunta a fazer, explicação de sua escolha da sua solução ou qualquer coisa que ache relevante, não hesite em compartilhar.

2017-11-30 12:30 UTC, MatheusRich commented
@Matheus456 Não linkou a issue

2017-12-01 01:24 UTC, Matheus456 commented
@MatheusRich Agora tem ;)

2017-12-01 11:41 UTC, MatheusRich commented on src/router/index.js
> +    {
Essa rota não é mais necessária, pode excluí-la.

2017-12-01 21:53 UTC, drianne commented
@MatheusRich , feito.

2017-12-02 15:29 UTC, alaxalves requested changes

2017-12-02 15:29 UTC, alaxalves commented on src/main.js
> +// import { Bar,Line } from 'vue-chart-js';
Por que isso ta comentado?

2017-12-02 17:05 UTC, alaxalves submitted a review, later dismissed

2017-12-02 17:05 UTC, alaxalves commented on src/components/Sprints/Sprint.vue
> +import Velocity from './Velocity.vue';
Isso ta funcionando?? Acredito que seja '../Velocity.vue' não? Já que o componente está dentro de Sprints.

2017-12-02 17:10 UTC, drianne commented on src/components/Sprints/Sprint.vue
> +import Velocity from './Velocity.vue';
Funciona dessa forma mesmo...

2017-12-02 17:17 UTC, drianne commented on src/main.js
> +// import { Bar,Line } from 'vue-chart-js';
Pronto,removi.

2017-12-02 18:04 UTC, MatheusRich approved these changes

2017-12-02 18:05 UTC, merged