Passando gráfico burndown para a biblioteca ChartJS
falko-org/Falko pull request #226
Opened 2017-12-05 17:44 UTC by MateusO97

## Mudanças Propostas

Modificando Burndown utilizando a biblioteca ChartJS para deixar o código padronizado.

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [x] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [x] Não há erros de linter.
- [x] A build está passando (testes, code climate e codacy).
- [x] O pull request está linkado à uma issue existente.

## Screenshots
![burndown_chartjs](https://user-images.githubusercontent.com/27258892/33621752-01b2908e-d9d3-11e7-8602-6d6f11a982d4.png)

2017-12-07 12:09 UTC, alaxalves commented
@MateusO97 Ficou muito bom, o código fica bem mais exuto com essa biblioteca.

2017-12-07 12:13 UTC, alaxalves requested changes

2017-12-07 12:13 UTC, alaxalves commented on src/components/Sprints/Burndown.vue
> +            yAxes: [
O correto seria _xAxis_ e _yAxis_. :D

2017-12-07 12:13 UTC, alaxalves commented on src/components/Sprints/Burndown.vue
> +            fill: false,
O que esse atributo representa??

2017-12-07 23:53 UTC, MateusO97 commented on src/components/Sprints/Burndown.vue
> +            fill: false,
Qual desses ? A label indica o nome do gráfico, que é do Burndown atual da sprint. fill é para não preencher o que esteja abaixo da linha do gráfico

2017-12-07 23:53 UTC, MateusO97 commented on src/components/Sprints/Burndown.vue
> +            yAxes: [
Obrigado, vou arrumar :D

2017-12-09 16:44 UTC, ThalissonMelo approved these changes

2017-12-09 16:48 UTC, merged