Concentando kanban e backlog para listar e mover corretamente
falko-org/Falko pull request #244
Opened 2017-12-10 05:00 UTC by ThalissonMelo

## Mudanças Propostas

Arrumando o kanban para alocar, e fazer reopen além de arrumar o backlog que não estava listando corretamente

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [x] Conserto de Bug
- [ ] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [x] Não há erros de linter.
- [x] A build está passando (testes, code climate e codacy).
- [x] O pull request está linkado à uma issue existente.

2017-12-10 15:15 UTC, alaxalves submitted a review, later dismissed
Arruma o nome do PR também.

2017-12-10 15:15 UTC, alaxalves commented on src/components/Issues/Issues.vue
> +          console.log(issues);
Acredito que esse console.log() nao é necessario

2017-12-10 18:16 UTC, ThalissonMelo commented on src/components/Issues/Issues.vue
> +          console.log(issues);
É verdade,  vou retirar.

2017-12-11 12:17 UTC, alaxalves requested changes

2017-12-11 12:17 UTC, alaxalves commented on src/components/Issues/Issues.vue
> +                  <p>{{ issue.name }}</p>
Porque tu tirou isso?? Vc fez merge com a devel? Olha aqui https://github.com/fga-gpp-mds/Falko-2017.2-FrontEnd/pull/213/files

2017-12-11 12:25 UTC, alaxalves commented on src/components/Issues/Issues.vue
> +                  <p>{{ issue.name }}</p>
Isso daí o @danieloda usa pra poder corrigir o bug de nome de issues.

2017-12-11 16:58 UTC, alaxalves approved these changes

2017-12-11 16:58 UTC, merged