Us24 visualizar grafico de issues
falko-org/Falko pull request #245
Opened 2017-12-10 05:51 UTC by Matheus456

## Mudanças Propostas

Criação da Dashboard de issues na página do projeto

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [x] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros de linter.
- [ ] A build está passando (testes, code climate e codacy).
- [x] O pull request está linkado à uma issue existente.

## Screenshots

/home/matheusroberto/Imagens/dashboard.png

## Outros Comentários

Só funciona com o back, mas ainda está faltando fazer os testes.

2017-12-10 15:50 UTC, alaxalves requested changes

2017-12-10 15:50 UTC, alaxalves commented on src/components/Issues/IssuesGraphic.vue
> +            <h4 class="modal-title">Set a interval</h4>
O correto aqui é "Set an interval"  :1st_place_medal: :

2017-12-10 15:50 UTC, alaxalves commented on src/components/Issues/IssuesGraphic.vue
> +            yAxes: [
O correto é "Axis"

2017-12-10 15:50 UTC, alaxalves commented on src/components/Issues/IssuesGraphic.vue
> +      if (sumOfClosedIssues == 0) {
Acredito que para o tipo de comparação que vc quer fazer aqui,o correto seria usar o comparador:
``` javascript 
=== 
```
Correto, @matheussbernardo @MatheusRich ??

2017-12-10 15:51 UTC, alaxalves commented
@Matheus456 Alem do mais existem alguns conflitos.

2017-12-10 15:51 UTC, alaxalves commented
@Matheus456 No geral, quando ao estilo achei muito bonito. Parabéns pelo ótimo trabalho.

2017-12-10 20:05 UTC, Matheus456 commented on src/components/Issues/IssuesGraphic.vue
> +            <h4 class="modal-title">Set a interval</h4>
Beleza! Vou arrumar.

2017-12-10 20:07 UTC, Matheus456 commented on src/components/Issues/IssuesGraphic.vue
> +            yAxes: [
Isso é padrão do chartjs

2017-12-10 20:09 UTC, Matheus456 commented
Beleza, assim que eu chegar em casa arrumo isso. Muito obrigado, @alaxalves <3

2017-12-10 20:11 UTC, Matheus456 commented
Vendo agora, acho que vou tentar arrumar a barra do closed issues, que está muito grudada com o fim do card.

2017-12-11 00:03 UTC, Matheus456 commented
Com a atualização:


![Final_Dashboard_chartjs](https://imgur.com/a/iFLZY.png)

2017-12-11 00:05 UTC, Matheus456 commented
@alaxalves Resolvi os pontos que você falou, só não troquei o comparador por "===".

2017-12-11 12:21 UTC, alaxalves commented
Pq não trocou o comparador @Matheus456 ? Dá uma olhada nesse link sobre o [ Operador '===' ](https://www.devmedia.com.br/javascript-como-e-quando-utilizar-os-operadores-e/37782)

2017-12-11 16:50 UTC, alaxalves approved these changes

2017-12-11 16:50 UTC, merged

2017-12-12 13:50 UTC, cantuariavc commented
Resolve a issue #222