Adição de confirmação antes do logout
falko-org/Falko pull request #315
Opened 2018-02-07 22:19 UTC by MatheusRich

## Mudanças Propostas

Adição de confirmação antes do logout.

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [ ] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [ ] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [ ] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros de linter.
- [ ] A build está passando (testes, code climate e codacy).
- [ ] O pull request está linkado à uma issue existente.

## Screenshots
![image](https://user-images.githubusercontent.com/20938712/35944580-1488dcb0-0c44-11e8-90e9-312bb06cf3b3.png)

2018-02-07 23:24 UTC, MartinsLucas approved these changes

2018-02-07 23:37 UTC, MartinsLucas requested changes
Por favor revise os testes referentes à funcionalidade. Eles devem ser modificados, pois o fluxo para realizar o logout foi alterado.

2018-02-09 00:00 UTC, MatheusRich commented
@MartinsLucas Não havia necessidade de refatorar os testes, pois o Cypress é configurado para aceitar automaticamente os eventos de janela (veja no print abaixo).

![image](https://user-images.githubusercontent.com/20938712/36004220-af2f2ca4-0d18-11e8-8fce-9c21d83d90f7.png)

Entretanto, para melhorar o teste eu fiz uma asserção quanto ao conteúdo da janela.

2018-02-09 00:57 UTC, MatheusRich commented
@MartinsLucas Foi necessário consertar um teste unitário também. Agora a build está passando.

2018-02-09 01:56 UTC, MartinsLucas approved these changes

2018-02-09 01:56 UTC, merged