Padronizando estilo dos botões da modal de todos os componentes
falko-org/Falko pull request #93
Opened 2017-11-03 19:23 UTC by Matheus456

Signed-off-by: Matheus Roberto <matheus456456@gmail.com>

## Mudanças Propostas

Descreva brevemente as mudanças feitas. Tenha certeza que linkou o pull request à uma issue existente.

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [x] Nova Feature

## Checklist

_Marque um `x` ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros de linter.
- [ ] A build está passando (testes, code climate e codacy).
- [ ] O pull request está linkado à uma issue existente.

## Screenshots
Se  possível, incluir screenshots das modificações  feitas.

## Outros Comentários
Se for uma mudança relativamente grande/complexa e você tiver algum comentário/pergunta a fazer, explicação de sua escolha da sua solução ou qualquer coisa que ache relevante, não hesite em compartilhar.

2017-11-04 17:43 UTC, alaxalves commented
@Matheus456 Acabei de aceitar o PR que muda a estrutura de pastas do projeto, só atualize a sua branch com a _devel_ e atualize o PR ;)

2017-11-04 17:44 UTC, alaxalves commented
@Matheus456 Me manda um print de como ficou essa padronização de botões que vc fez e não esqueça de atualizar o template do Pull Request

2017-11-05 03:40 UTC, Matheus456 commented
Pronto, as imagens estão ai! Ela já está pronta para dar o merge, não deu nenhum conflito.

2017-11-05 13:14 UTC, alaxalves commented
Surgiram novos conflitos já que eu aceitei alguns PRs, dá uma olhada neles e manda de novo que estarão prontos pra mergir

2017-11-05 13:14 UTC, alaxalves requested changes
arruma os conflitos e manda dnv

2017-11-05 18:52 UTC, alaxalves commented
Boa @Matheus456 !! PR Aceito

2017-11-05 18:54 UTC, alaxalves approved these changes

2017-11-05 18:54 UTC, merged